# Generated by Django 5.2.16 on 2026-07-18 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('special_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
